import Head from 'next/head'
import { MyTrips } from '@autospace-org/ui/src/components/templates/MyTrips'
import { useAppSelector } from '@autospace-org/store'
import { selectUid, selectUser } from '@autospace-org/store/user'

import { AlertSection } from '@autospace-org/ui/src/components/organisms/AlertSection'
import { Container } from '@autospace-org/ui/src/components/atoms/Container'

export default function Login() {
  const { uid, loaded } = useAppSelector(selectUser)
  return (
    <>
      <Head>
        <title>Login | Autospace | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-25">
        <Container>
          {uid ? (
            <MyTrips uid={uid} />
          ) : (
            <AlertSection>You are not logged in.</AlertSection>
          )}
        </Container>
      </main>
    </>
  )
}
