import Head from 'next/head'
import { AuthLayout } from '@autospace-org/ui/src/components/molecules/AuthLayoutSimple'
import { AlertSection } from '@autospace-org/ui/src/components/organisms/AlertSection'

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AuthLayout title="Register">
          <AlertSection>
            Contact your manager to add you as a valet.
          </AlertSection>
        </AuthLayout>
      </main>
    </>
  )
}
