import { Container } from '@autospace-org/ui/src/components/atoms/Container'
import { ManageValets } from '@autospace-org/ui/src/components/templates/ManageValets'
import Head from 'next/head'

export default function Login() {
  return (
    <>
      <Head>
        <title>Manage valets | Autospace | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <ManageValets />
        </Container>
      </main>
    </>
  )
}
