import Head from 'next/head'
import { CustomerBookings } from '@autospace-org/ui/src/components/templates/CustomerBookings'
import { Container } from '@autospace-org/ui/src/components/atoms/Container'

export default function Bookings() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <CustomerBookings />
        </Container>
      </main>
    </>
  )
}
