import Head from 'next/head'
import { HowItWorksCustomer } from '@autospace-org/ui/src/components/templates/HowItWorksCustomer'
import { Container } from '@autospace-org/ui/src/components/atoms/Container'

export default function Search() {
  return (
    <>
      <Head>
        <title>Autospace - How it works?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HowItWorksCustomer />
      </main>
    </>
  )
}
